# Generated by Django 4.2.5 on 2023-09-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='publish',
            field=models.DateTimeField(),
        ),
    ]
