# Generated by Django 4.2.5 on 2023-09-15 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_upload_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 8, 31, 24, 655315, tzinfo=datetime.timezone.utc)),
        ),
    ]
