# Generated by Django 4.2.5 on 2023-09-15 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_upload_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
